config/routes.rb
Rails.application.routes.draw do  
  resources :shop_addresses
  devise_for :users
  root "categories#index"
  resources :categories
  resources :products do
    resources :variants
    post :import, on: :collection
  end
  resources :user_roles    
end

app/views/shared/_csv_import.html.erb
<div>
  <%= form_tag import_products_path, method: :post, multipart: true do %>
    <%= file_field_tag :file, accept: ".csv" %>
    <%= submit_tag 'Import' %>
  <% end %>
</div>

app/views/shared/_form_errors.html.erb
<% if object.errors.any? %>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">BechaKena</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Categories", categories_url, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Products", products_url, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
      <div class="d-flex">
        <% if user_signed_in? %>
          <%= button_to "Log Off #{current_user.username}", destroy_user_session_path, method: :delete, class: "btn btn-primary" %>
          <% else %>
          <%= link_to "Login", new_user_session_path, class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_variants_form.html.erb
<div class="row mb-3">
    <%= variant_form.label :color, class:"col-sm-2 col-form-label" %>
  <div class="col-sm-10">
  <%= variant_form.text_field :color, placeholder: "Product color", class: "form-control" %>
  </div>
</div>
<div class="row mb-3">
    <%= variant_form.label :size, class:"col-sm-2 col-form-label" %>
  <div class="col-sm-10">
  <%= variant_form.text_field :size, placeholder: "Small/Medium/Large", class: "form-control" %>
  </div>
</div>
<div class="row mb-3">
    <%= variant_form.label :sku, class:"col-sm-2 col-form-label" %>
  <div class="col-sm-10">
  <%= variant_form.text_field :sku, placeholder: "redsm*****", class: "form-control" %>
  </div>
</div>