config/routes.rb
Rails.application.routes.draw do  
  resources :shop_addresses
  devise_for :users
  root "categories#index"
  resources :categories
  resources :products do
    resources :variants
    post :import, on: :collection
  end
  resources :user_roles    
end

app/controllers/user_roles_controller.rb
class UserRolesController < ApplicationController
  def index
    if current_user.super_admin?
    @users = User.all
    else
      redirect_to user_role_path(current_user)
    end
  end

  def show
    authorize :user_role, :show?

    find_user
  end

  def edit
    find_user
  end

  def update
    find_user
    if User.update(user_params)
      redirect_to :user_role_path, notice:  "User info updated successfully"
    else
      redirect_to :edit, notice: "Something went wrong"
    end
  end

  private
    def find_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :username, :email, :roles)
    end

end

app/views/user_roles/edit.html.erb
<div class="row mt-4">
  <div class="col-3"></div>
  <div class="col-6">
    <h3>Edit User Details </h3>
      <div class="mt-3 container-fluid">
        <%= form_with url: user_role_path do |form| %>
        <div class="row mb-3">
            <%= form.label :name, class:"col-sm-2 col-form-label" %>
          <div class="col-sm-10">
          <%= form.text_field :name, placeholder: "Full Name", class: "form-control" %>
          </div>
        </div>
        <div class="row mb-3">
            <%= form.label :username, class:"col-sm-2 col-form-label" %>
          <div class="col-sm-10">
          <%= form.text_field :username, placeholder: "Username", class: "form-control" %>
          </div>
        </div>
         <div class="row mb-3">
            <%= form.label :email, class:"col-sm-2 col-form-label" %>
          <div class="col-sm-10">
          <%= form.text_field :email, placeholder: "email", class: "form-control" %>
          </div>
        </div>
        <div class="row mb-3">
            <%= form.label :roles, class:"col-sm-2 col-form-label" %>
          <div class="col-sm-10">
          <%= form.select :roles, (User::USER_ROLES).map {|n| [n.capitalize, n]} , class: "form-control form-select" %>

          </div>
        </div>
        <br>
        <div>
          <%= form.submit "Update", class:"btn btn-primary" %>
        </div>
      <% end %>
  <div class="col-3"></div>
</div>

app/views/user_roles/index.html.erb
<div class="row mt-3">
  <div class="col">
    <h3>All Users</h3>
  </div>
</div>

<div class="row mt-3">
  <div class="col">
    <%# <%= link_to "Add User", new_user_url(@user), class:"btn btn-primary" %>
  </div>
  <div class="col"></div>
  <div class="col"></div>
</div>


<div class="row mt-3">
  <div class="col">
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Username</th>
          <th scope="col">Email ID</th>
          <th scope="col">Role</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |u| %>
        <tr>
          <td><%= u.name %></td>
          <td><%= u.username %></td>
          <td><%= u.email %></td>
          <td><%= u.roles.to_sentence %></td>
          <td>
            <%=link_to "View", user_role_path(u), class:" btn btn-info" %>
            <%= link_to "Edit", edit_user_role_path(u), class: "btn btn-warning" %>

          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/user_roles/show.html.erb
<div class="row mt-3">
  <div class="col">
    <h3>User Details</h3>
  </div>
</div>

<div class="row mt-3">
  <div class="col">
    <%# <%= link_to "Add User", new_user_url(@user), class:"btn btn-primary" %>
  </div>
  <div class="col"></div>
  <div class="col"></div>
</div>


<div class="row mt-3">
  <div class="col">
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Username</th>
          <th scope="col">Email ID</th>
          <th scope="col">Role</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @user.name %></td>
          <td><%= @user.username %></td>
          <td><%= @user.email %></td>
          <td><%= @user.roles.to_sentence %></td>
          <td>
            <%= link_to "View", user_role_path(@user), class:" btn btn-info" %>
            <%= link_to "Edit", edit_user_role_path(@user), class: "btn btn-warning" %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>