config/routes.rb
Rails.application.routes.draw do  
  resources :shop_addresses
  devise_for :users
  root "categories#index"
  resources :categories
  resources :products do
    resources :variants
    post :import, on: :collection
  end
  resources :user_roles    
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :category, optional: true
  has_many :categories 
  has_many :products, dependent: :destroy 

  scope :main_categories, -> {where(category_id: nil)}
end

# == Schema Information
#
# Table name: categories
#
#  id            :bigint           not null, primary key
#  details       :text
#  name          :string           not null
#  product_count :integer          default(0)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  category_id   :bigint
#

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    # @categories = SearchCategory.new(params[:search]).call
    @categories = SearchCategory.call(params[:search])

    authorize @categories

    respond_to do |format|
      format.html{}
      format.csv{send_data GenerateCategoryCsv.new(@categories).call, filename: "Category-#{Date.today}.csv"}
    end

  end

  def show
    find_category
    authorize @category
  end

  def new
    @category = Category.new
    authorize @category
  end

  def create
    @category = Category.new(category_params)

    authorize @category

    if @category.save
      CategoryMailer.info_email(@current_user).deliver_later
      redirect_to category_url(@category)
    else
      render :new
    end
  end

  def edit
    find_category
  end

  def update
    find_category

    if @category.update(category_params)
      redirect_to @category
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    find_category
    @category.destroy
    redirect_to root_path, status: :see_other
  end

  private

    def find_category
      @category = Category.find(params[:id])
    end

    def category_params
      #using strong parameters
      params.require(:category).permit(:name, :category_id, :details)

    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<div class="row mt-4">
  <div class="col-3"></div>
  <div class="col-6">
    <h3>Edit <%@category.name %> </h3>
      <div class="mt-3 container-fluid">
        <%= form_with model: @category do |form| %>
        <div class="row mb-3">
            <%= form.label :name, class:"col-sm-2 col-form-label" %>
          <div class="col-sm-10">
          <%= form.text_field :name, placeholder: "Category Name", class: "form-control" %>
          </div>
        </div>
        <div class="row mb-3">
            <%= form.label :details, class:"col-sm-2 col-form-label" %>
          <div class="col-sm-10">
          <%= form.text_field :details, placeholder: "Details", class: "form-control" %>
          </div>
        </div>
        <div class="row mb-3">
            <%= form.label :category_id, class:"col-sm-2 col-form-label" %>
          <div class="col-sm-10">
          <%= form.select :category_id, Category.where(category_id: nil).map { |c| [c.name, c.id] }, class: "form-control form-select" %>
          </div>
        </div>
        <br>
        <div>
          <%= form.submit "Update", class:"btn btn-primary" %>
        </div>
      <% end %>
  <div class="col-3"></div>
</div>

app/views/categories/index.html.erb
<div class="row mt-3">
  <div class="col">
    <h3>All Categories</h3>
  </div>
</div>

<div class="row mt-3">
  <div class="col">
    <% if policy(Category).new? %>
    <% # if policy(:user_role).new? %>

      <%= link_to "Add Category", new_category_url, class:"btn btn-primary" %>
    <% end %>
    <%= link_to "Download CSV", categories_url(format: :csv), class:"btn btn-primary" %>

  </div>
  <div class="col"></div>
  <div class="col">
    <%= form_tag(categories_path, method: :get) do %>
      <%= text_field_tag(:search, params[:search]) %>
      <%= submit_tag("Search") %>
    <% end %>
  </div>
</div>


<div class="row mt-3">
  <div class="col">
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Parent Category</th>
          <th scope="col">Product Count</th>
          <th scope="col">Details</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        <% @categories.each do |category| %>
        <tr>
          <td><%= category.name %></td>
          <td><%= category.category&.name %></td>
          <td><%= category.product_count %></td>
          <td><%= category.details %></td>
          <td>
            <%=link_to "View", category, class:" btn btn-info" %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/categories/new.html.erb
<div class="row mt-4">
  <div class="col-3"></div>
  <div class="col-6">
    <h3>Create new category</h3>
      <div class="mt-3 container-fluid">
        <%= form_with model: @category do |form| %>
          <div class="row mb-3">
              <%= form.label :name, class:"col-sm-2 col-form-label" %>
            <div class="col-sm-10">
            <%= form.text_field :name, placeholder: "Category Name", class: "form-control" %>
            </div>
          </div>
          <div class="row mb-3">
              <%= form.label :details, class:"col-sm-2 col-form-label" %>
            <div class="col-sm-10">
            <%= form.text_field :details, placeholder: "Details", class: "form-control" %>
            </div>
          </div>
          <div class="row mb-3">
              <%= form.label :category_id, class:"col-sm-2 col-form-label" %>
            <div class="col-sm-10">
            <%= form.select :category_id, Category.where(category_id: nil).map { |c| [c.name, c.id] }, class: "form-control form-select" %>
            </div>
          </div>
          <br>
          <div>
            <%= form.submit "Create", class:"btn btn-primary" %>
          </div>
      <% end %>
  <div class="col-3"></div>
</div>

app/views/categories/show.html.erb
<div class="row mt-3">
  <div class="col">
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%= @category.name %> Details</h5>
        <h6 class="card-subtitle mb-2 text-body-secondary">
          <%=
            if @category.category
              "Sub Category"
             else
              "Main Category"
            end
          %>
        </h6>
        <p class="card-text"><%= @category.details %></p>
        <div>
        <%= link_to "Add new", new_category_url, class:"btn btn-primary" %>

        <%= link_to "edit", edit_category_url(@category), class:"btn btn-warning" %>
        <%= button_to "Delete", category_path(@category), method: :delete, class: "btn btn-danger" %>
        </div>
      </div>
    </div>
  </div>
</div>