config/routes.rb
Rails.application.routes.draw do  
  resources :shop_addresses
  devise_for :users
  root "categories#index"
  resources :categories
  resources :products do
    resources :variants
    post :import, on: :collection
  end
  resources :user_roles    
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :variants, dependent: :destroy
end

# == Schema Information
#
# Table name: products
#
#  id          :bigint           not null, primary key
#  description :text
#  name        :string
#  price       :decimal(, )
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :bigint           not null
#
# Indexes
#
#  index_products_on_category_id  (category_id)
#
# Foreign Keys
#
#  fk_rails_...  (category_id => categories.id)
#

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    if params[:search].present?
      @products = Product.where("name ILIKE ?", "%#{params[:search]}%")
    else
    @products = Product.all
    end
  end

  def import
  #   return redirect_to request.referer, notice: 'No file added' if params[:file].nil?
  #   return redirect_to request.referer, notice: 'Only CSV files allowed' unless params[:file].content_type == 'text/csv'
    ImportProductsCsv.new(params[:file]).call
    redirect_to root_path, notice: 'Import started...'
  end

  def show
    find_product
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      # category = @product.category
      # product_count = category.product_count
      # category.update(product_count: product_count + 1)

      ProductCountJob.set(wait: 1.minute).perform_later(@product)

      redirect_to product_url(@product)
    else
      render :new
    end
  end

  def edit
    find_product
  end

  def update
    find_product

    if @product.update(product_params)
      redirect_to product_url(@product)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    find_product
    @product.destroy
    redirect_to root_path, status: :see_other
  end

  private

  def find_product
    @product = Product.find(params[:id])
  end

  def product_params
    #using strong parameters
    params.require(:product).permit(:name, :description, :price, :category_id)
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<div class="row mt-4">
  <div class="col-3"></div>
  <div class="col-6">
    <h3>Update <%=@product.name %></h3>
      <div class="mt-3 container-fluid">
        <%= form_with model: @product do |form| %>
          <div class="row mb-3">
              <%= form.label :name, class:"col-sm-2 col-form-label" %>
            <div class="col-sm-10">
            <%= form.text_field :name, placeholder: "Product Name", class: "form-control" %>
            </div>
          </div>
          <div class="row mb-3">
              <%= form.label :description, class:"col-sm-2 col-form-label" %>
            <div class="col-sm-10">
            <%= form.text_field :details, placeholder: "Details", class: "form-control" %>
            </div>
          </div>
          <div class="row mb-3">
              <%= form.label :price, class:"col-sm-2 col-form-label" %>
            <div class="col-sm-10">
            <%= form.text_field :price, placeholder: "Price", class: "form-control" %>
            </div>
          </div>
          <div class="row mb-3">
              <%= form.label :category_id, class:"col-sm-2 col-form-label" %>
            <div class="col-sm-10">
            <%= form.select :category_id, Category.where.not(category_id: nil).map { |c| [c.name, c.id] }, class: "form-control form-select" %>
            </div>
          </div>
          <br>
          <div>
            <%= form.submit "Update", class:"btn btn-primary" %>
          </div>
      <% end %>
  <div class="col-3"></div>
</div>

app/views/products/index.html.erb
<div class="row mt-3">
  <div class="col">
    <h3>All Products</h3>
  </div>
</div>

<div class="row mt-3">
  <div class="col">
    <%= link_to "Add Product", new_product_url(@product), class:"btn btn-primary" %>
  </div>
  <div class="col">
    <%# Rendering the csv import form  %>
    <%= render "shared/csv_import" %>
  </div>
</div>

<div class="row mt-3">
  <div class="col"></div>
  <div class="col"></div>
  <div class="col">
    <%= form_tag(products_path, method: :get) do %>
      <%= text_field_tag(:search, params[:search]) %>
      <%= submit_tag("Search") %>
    <% end %>
  </div>
</div>

<div class="row mt-3">
  <div class="col">
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Product Name</th>
          <th scope="col">Parent Category</th>
          <th scope="col">Price</th>
          <th scope="col">Product Action</th>
        </tr>
      </thead>
      <tbody>
        <% @products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.category&.name %></td>
          <td><%= product.price %></td>
          <td>
            <div class="row">
              <div class="col">
                <%= link_to "edit", edit_product_url(product), class:"btn btn-warning" %>
                <%= link_to "View", product_url(product), class: "btn btn-info" %>
              </div>
            </div>          
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/products/nestednew.html.erb
<div class="row mt-4">
  <div class="col-3"></div>
  <div class="col-6">
    <%# <%= render "csv_import" %>
    <h3>Create new Product</h3>
      <div class="mt-3 container-fluid">
        <%= form_with model: @product do |form| %>
          <div class="row mb-3">
              <%= form.label :name, class:"col-sm-2 col-form-label" %>
            <div class="col-sm-10">
            <%= form.text_field :name, placeholder: "Product Name", class: "form-control" %>
            </div>
          </div>
          <div class="row mb-3">
              <%= form.label :description, class:"col-sm-2 col-form-label" %>
            <div class="col-sm-10">
            <%= form.text_field :details, placeholder: "Details", class: "form-control" %>
            </div>
          </div>
          <div class="row mb-3">
              <%= form.label :price, class:"col-sm-2 col-form-label" %>
            <div class="col-sm-10">
            <%= form.text_field :price, placeholder: "Price", class: "form-control" %>
            </div>
          </div>
          <div class="row mb-3">
              <%= form.label :category_id, class:"col-sm-2 col-form-label" %>
            <div class="col-sm-10">
            <%= form.select :category_id, Category.where(category_id: present?).map { |c| [c.name, c.id] }, class: "form-control form-select" %>
            </div>
          </div>
          <br>
          <div>
            <%= form.submit "Create", class:"btn btn-primary" %>
          </div>
      <% end %>
  <div class="col-3"></div>
</div>

app/views/products/new.html.erb
<div class="row mt-4">
  <div class="col-3"></div>
  <div class="col-6">
    <%# <%= render "csv_import" %>
    <h3>Create new Product</h3>
      <div class="mt-3 container-fluid">
        <%= form_with model: @product do |form| %>
          <div class="row mb-3">
              <%= form.label :name, class:"col-sm-2 col-form-label" %>
            <div class="col-sm-10">
            <%= form.text_field :name, placeholder: "Product Name", class: "form-control" %>
            </div>
          </div>
          <div class="row mb-3">
              <%= form.label :description, class:"col-sm-2 col-form-label" %>
            <div class="col-sm-10">
            <%= form.text_field :details, placeholder: "Details", class: "form-control" %>
            </div>
          </div>
          <div class="row mb-3">
              <%= form.label :price, class:"col-sm-2 col-form-label" %>
            <div class="col-sm-10">
            <%= form.text_field :price, placeholder: "Price", class: "form-control" %>
            </div>
          </div>
          <div class="row mb-3">
              <%= form.label :category_id, class:"col-sm-2 col-form-label" %>
            <div class="col-sm-10">
            <%= form.select :category_id, Category.where(category_id: present?).map { |c| [c.name, c.id] }, class: "form-control form-select" %>
            </div>
          </div>
          <br>
          <div>
            <%= form.submit "Create", class:"btn btn-primary" %>
          </div>
      <% end %>
  <div class="col-3"></div>
</div>

app/views/products/show.html.erb
<div class="row mt-3">
  <div class="col">
    <h3>Product Details</h3>
  </div>
</div>

<div class="row mt-3">
  <div class="col">
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Product Name</th>
          <th scope="col">Parent Category</th>
          <th scope="col">Price</th>
          <th scope="col">Product Details</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @product.name %></td>
          <td><%= @product.category&.name %></td>
          <td><%= @product.price %></td>
          <td><%= @product.description %> </td>
          <td><%= button_to "Delete", product_url(@product), method: :delete, class: "btn btn-danger" %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
<br>
<hr>
<hr>
<div>
<%= link_to "Add New Variant", new_product_variant_path(@product), class: "btn btn-info" %>
<%= link_to "Search Variant", new_product_variant_path(@product), class: "btn btn-info" %>
</div>

<h3>Variants</h3>
<div class="container d-flex flex-row">
  <% @product.variants.each do |variant| %>
  <div class="row mt-3">
    <div class="col">
      <div class="card  mx-auto" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">Variant ID#<%= variant.id%> Details</h5>
          <h6 class="card-subtitle mb-2 text-body-secondary">Variant color <%= variant.color%></h6>
          <h6 class="card-subtitle mb-2 text-body-secondary">Variant SKU <%= variant.sku %></h6>          
          <div class="row mt-2">
             <div class="col"> <%= link_to "edit", edit_product_variant_url(@product, variant), class:"btn btn-warning" %></div>
             <div class="col"> <%= button_to "Delete", product_variant_url(@product), method: :delete, class: "btn btn-danger" %></div>
             <div class="col"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>